---

- name: MY FIRST PLAYBOOK
  hosts: cisco_ios
  gather_facts: false
  connection: network_cli

  tasks:
    - name: "OSPF CONFIG"
      cisco.ios.ios_config:
        lines:
          - router-id {{ ospf_rid }}
        parents:
          - router ospf 1
      register: my_output

    - debug: var=my_output