# Ansible playbook to show ip route on cisco ios devices and print the output to screen

---

- name: Get IP routes
  hosts: R1
  gather_facts: false

  vars:
    cli:
      username: cisco
      password: cisco1
          
  tasks:
    - name: show IP route on devices
      raw: "show IP route"
      register: print_output
    - debug: var=print_output.stdout_lines
...
